const STORAGE_KEY = "supgeul_phase1_author_studio_v2";
export const CURRENT_USER_ID = "user_current";

const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;

function seedState() {
  const worldId = id("world");
  const workId = id("work");
  const ep0 = id("ep");
  const ep1 = id("ep");
  const itemId = id("item");
  const charId = id("char");
  const noticeCode = id("notice");
  return {
    users: [
      {
        id: CURRENT_USER_ID,
        displayName: "현재 사용자",
        officialNickname: "나무나비",
        officialNicknameUpdatedAt: now(),
        officialNicknameChangeTickets: 1,
        temporaryAuthorNicknameChangeTickets: 1,
        queueAddTickets: 2,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    authorProfile: {
      id: "author_profile_current",
      workspaceTitle: "숲글 작가 작업실",
      userId: CURRENT_USER_ID,
      adultVerificationStatus: "verified",
      readerGenreDisplay1: "여성향",
      readerGenreDisplay2: "창작 웹소설",
      createdAt: now(),
      updatedAt: now(),
    },
    works: [
      {
        id: workId,
        title: "비밀 숲의 선택자",
        type: "interactive",
        userId: CURRENT_USER_ID,
        temporaryAuthorNickname: "숲고지기",
        temporaryAuthorNicknameUpdatedAt: now(),
        description: "닫힌 숲에서 시작되는 선택형 연재입니다. 독자는 선택과 아이템에 따라 다른 장면을 보게 됩니다.",
        genre1: "여성향",
        genre2: "창작 웹소설",
        normalTags: ["FANTASY", "선택지", "숲"],
        sensitiveTags: ["민감할 수 있는 태그 예시"],
        isAdult: "all",
        adultEditable: true,
        status: "serializing",
        isPaidWork: false,
        cover: { mode: "color", color: "#47645e", showTitle: true },
        createdAt: now(),
        updatedAt: now(),
        episodeOrder: [ep0, ep1],
        worldbuildingId: worldId,
        releaseSettings: { method: "regular", days: ["월", "수", "금"], hour: "18", minute: "00", timezone: "Asia/Seoul" },
        views: 12,
        favorites: 7,
        comments: 2,
        nextEpisodeWaiters: 12,
        queueMaxSlots: 1,
        queueSupportTickets: 2,
        queueShowEmptySlots: true,
      },
    ],
    worldbuildings: [
      {
        id: worldId,
        ownerUserId: CURRENT_USER_ID,
        title: "비밀 숲 세계관",
        description: "숲, 열쇠, 문장 마법을 중심으로 둔 세계관입니다.",
        sourceScope: "me",
        externalSourceName: "",
        externalAuthorName: "",
        externalSourceLink: "",
        workIds: [workId],
        itemIds: [itemId],
        characterIds: [charId],
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    characters: [
      {
        id: charId,
        worldbuildingId: worldId,
        name: "주인공",
        authorLabel: "주인공",
        fullName: "한서린",
        publicDescription: "문장을 만지면 기억을 읽는 인물입니다.",
        privateDescription: "초반에는 능력을 숨깁니다.",
        image: "",
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    items: [
      {
        id: itemId,
        worldbuildingId: worldId,
        ownerUserId: CURRENT_USER_ID,
        name: "낡은열쇠",
        type: "main",
        priority: 3,
        tags: ["열쇠"],
        itemKind: "normal",
        defaultAddMessage: "낡은열쇠를 손에 넣었다.",
        defaultRemoveMessage: "낡은열쇠를 잃었다.",
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    episodes: [
      {
        id: ep0,
        workId,
        episodeNo: 0,
        requiredPreviousEpisodeNo: "",
        title: "프롤로그",
        body: "숲의 문이 열렸다.\n\n[[+낡은열쇠]]\n낡은열쇠를 손에 넣었다.\n\n[[선택지:\n문 안으로 들어간다.\n돌아선다.\n]]\n\n[[씬:문 안으로 들어간다.\n어둠 속에서 작은 불빛이 떠올랐다.\n]]",
        authorNote: "",
        status: "published",
        publishAt: now(),
        isPaid: false,
        price: 0,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: ep1,
        workId,
        episodeNo: 1,
        requiredPreviousEpisodeNo: 0,
        title: "첫 번째 문장",
        body: "문장 하나가 나무껍질 위에서 빛났다.",
        authorNote: "",
        status: "queued",
        publishAt: "",
        isPaid: false,
        price: 0,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    releases: [],
    noticeTemplates: [
      {
        id: id("template"),
        noticeCode,
        title: "연재 안내",
        body: "이번 주는 월, 수, 금 오후 6시에 공개됩니다.",
        noticeType: "manual",
        createdAt: now(),
        updatedAt: now(),
        isAutoGenerated: false,
      },
    ],
    workNotices: [
      { id: id("work_notice"), workId, noticeCode, createdAt: now(), updatedAt: now(), isAutoGenerated: false },
    ],
    homeIndex: [],
    authorState: { selectedWorkId: workId, editorDrafts: {}, lastSavedAt: "", unsavedChanges: false },
  };
}

function normalize(state) {
  const fallback = seedState();
  if (!state || typeof state !== "object" || Array.isArray(state)) state = fallback;
  if (!Array.isArray(state.users)) state.users = fallback.users;
  if (!state.authorProfile || typeof state.authorProfile !== "object" || Array.isArray(state.authorProfile)) state.authorProfile = fallback.authorProfile;
  if (!Array.isArray(state.works)) state.works = [];
  if (!Array.isArray(state.worldbuildings)) state.worldbuildings = [];
  if (!Array.isArray(state.characters)) state.characters = [];
  if (!Array.isArray(state.items)) state.items = [];
  if (!Array.isArray(state.episodes)) state.episodes = [];
  if (!Array.isArray(state.releases)) state.releases = [];
  if (!Array.isArray(state.noticeTemplates)) state.noticeTemplates = [];
  if (!Array.isArray(state.workNotices)) state.workNotices = [];
  if (!Array.isArray(state.homeIndex)) state.homeIndex = [];
  state.authorState ||= fallback.authorState;
  state.users[0] ||= fallback.users[0];
  state.users[0].officialNickname ||= "나무나비";
  state.users[0].officialNicknameChangeTickets ??= 1;
  state.users[0].temporaryAuthorNicknameChangeTickets ??= 1;
  state.users[0].queueAddTickets ??= 2;
  state.authorProfile.workspaceTitle ||= "숲글 작가 작업실";
  if (state.authorProfile.readerGenreDisplay1 === "자유") state.authorProfile.readerGenreDisplay1 = "마음대로";
  state.authorProfile.readerGenreDisplay1 ||= "여성향";
  state.authorProfile.readerGenreDisplay2 ||= "창작 웹소설";
  state.authorProfile.adultVerificationStatus ||= "none";
  state.works.forEach((work) => {
    work.userId ||= CURRENT_USER_ID;
    if (work.genre1 === "자유") work.genre1 = "마음대로";
    work.normalTags ||= work.workTags || [];
    work.sensitiveTags ||= [];
    work.episodeOrder ||= [];
    work.releaseSettings ||= { method: "irregular", days: [], hour: "18", minute: "00", timezone: "Asia/Seoul" };
    work.cover ||= { mode: "color", color: "#47645e", showTitle: true };
    work.cover.mode ||= "color";
    work.cover.color ||= "#47645e";
    work.cover.imageData ||= "";
    work.cover.imageName ||= "";
    work.nextEpisodeWaiters ??= 0;
    work.queueMaxSlots ??= 1;
    work.queueSupportTickets ??= 2;
    work.queueShowEmptySlots ??= true;
  });
  state.worldbuildings.forEach((world) => {
    world.sourceScope ||= "me";
    world.externalSourceName ||= "";
    world.externalAuthorName ||= "";
    world.externalSourceLink ||= "";
  });
  state.characters.forEach((character) => {
    character.authorLabel ||= character.name || "";
    character.name ||= character.authorLabel;
    character.fullName ||= "";
    character.image ||= "";
  });
  state.episodes.forEach((episode) => {
    episode.requiredPreviousEpisodeNo ??= "";
    if (episode.status === "reserved") episode.status = "confirmed";
  });
  return state;
}

let cache = null;

export function loadState() {
  if (cache) return cache;
  const raw = localStorage.getItem(STORAGE_KEY);
  let parsed = null;
  try {
    parsed = raw ? JSON.parse(raw) : seedState();
  } catch {
    parsed = seedState();
  }
  cache = normalize(parsed);
  saveState(cache);
  return cache;
}

export function saveState(state = cache) {
  cache = normalize(state || seedState());
  localStorage.setItem(STORAGE_KEY, JSON.stringify(cache));
}

export function resetState() {
  cache = seedState();
  saveState(cache);
  return cache;
}

export function exportState() {
  return JSON.stringify(loadState(), null, 2);
}

export function timestamp() {
  return now();
}

export function uid(prefix) {
  return id(prefix);
}

export function currentUser() {
  return loadState().users.find((user) => user.id === CURRENT_USER_ID) || loadState().users[0];
}

export function displayAuthor(work) {
  if (work.temporaryAuthorNickname) return work.temporaryAuthorNickname;
  return loadState().users.find((user) => user.id === work.userId)?.officialNickname || "작가명 없음";
}

export function workWorld(work) {
  return loadState().worldbuildings.find((world) => world.id === work.worldbuildingId);
}

export function workEpisodes(workId) {
  return loadState()
    .episodes.filter((episode) => episode.workId === workId)
    .sort((a, b) => Number(a.episodeNo) - Number(b.episodeNo));
}

export function noticeTemplate(noticeCode) {
  return loadState().noticeTemplates.find((notice) => notice.noticeCode === noticeCode);
}

export function upsert(collection, entity) {
  const state = loadState();
  const list = state[collection];
  const index = list.findIndex((item) => item.id === entity.id);
  if (index >= 0) list[index] = { ...list[index], ...entity, updatedAt: now() };
  else list.push({ ...entity, createdAt: now(), updatedAt: now() });
  saveState(state);
  return entity;
}
