const STORAGE_KEY = "supgeul_phase1_author_studio_v2";
export const CURRENT_USER_ID = "user_current";

const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;

function seedState() {
  const worldId = id("world");
  const workId = id("work");
  const ep0 = id("ep");
  const ep1 = id("ep");
  const itemId = id("item");
  const charId = id("char");
  const noticeCode = id("notice");
  return {
    users: [
      {
        id: CURRENT_USER_ID,
        displayName: "현재 사용자",
        officialNickname: "나무나비",
        officialNicknameUpdatedAt: now(),
        officialNicknameChangeTickets: 1,
        temporaryAuthorNicknameChangeTickets: 1,
        queueAddTickets: 2,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    authorProfile: {
      id: "author_profile_current",
      workspaceTitle: "숲글 작가 작업실",
      userId: CURRENT_USER_ID,
      adultVerificationStatus: "verified",
      readerGenreDisplay1: "여성향",
      readerGenreDisplay2: "창작 웹소설",
      createdAt: now(),
      updatedAt: now(),
    },
    works: [
      {
        id: workId,
        title: "비밀 숲의 선택자",
        type: "interactive",
        userId: CURRENT_USER_ID,
        temporaryAuthorNickname: "숲고지기",
        temporaryAuthorNicknameUpdatedAt: now(),
        description: "닫힌 숲에서 시작되는 선택형 연재입니다. 독자는 선택과 아이템에 따라 다른 장면을 보게 됩니다.",
        genre1: "여성향",
        genre2: "창작 웹소설",
        normalTags: ["FANTASY", "선택지", "숲"],
        sensitiveTags: ["민감할 수 있는 태그 예시"],
        isAdult: "all",
        adultEditable: true,
        status: "serializing",
        isPaidWork: false,
        cover: { mode: "color", color: "#47645e", showTitle: true },
        createdAt: now(),
        updatedAt: now(),
        episodeOrder: [ep0, ep1],
        worldbuildingId: worldId,
        releaseSettings: { method: "regular", days: ["월", "수", "금"], hour: "18", minute: "00", timezone: "Asia/Seoul" },
        views: 12,
        favorites: 7,
        comments: 2,
        nextEpisodeWaiters: 12,
        queueMaxSlots: 1,
        queueSupportTickets: 2,
        queueShowEmptySlots: true,
      },
    ],
    worldbuildings: [
      {
        id: worldId,
        ownerUserId: CURRENT_USER_ID,
        title: "비밀 숲 세계관",
        description: "숲, 열쇠, 문장 마법을 중심으로 둔 세계관입니다.",
        sourceScope: "me",
        externalSourceName: "",
        externalAuthorName: "",
        externalSourceLink: "",
        workIds: [workId],
        itemIds: [itemId],
        characterIds: [charId],
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    characters: [
      {
        id: charId,
        worldbuildingId: worldId,
        name: "주인공",
        authorLabel: "주인공",
        fullName: "한서린",
        publicDescription: "문장을 만지면 기억을 읽는 인물입니다.",
        privateDescription: "초반에는 능력을 숨깁니다.",
        image: "",
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    items: [
      {
        id: itemId,
        worldbuildingId: worldId,
        ownerUserId: CURRENT_USER_ID,
        name: "낡은열쇠",
        type: "main",
        priority: 3,
        tags: ["열쇠"],
        itemKind: "normal",
        defaultAddMessage: "낡은열쇠를 손에 넣었다.",
        defaultRemoveMessage: "낡은열쇠를 잃었다.",
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    episodes: [
      {
        id: ep0,
        workId,
        episodeNo: 0,
        requiredPreviousEpisodeNo: "",
        title: "프롤로그",
        body: "숲의 문이 열렸다.\n\n[[+낡은열쇠]]\n낡은열쇠를 손에 넣었다.\n\n[[선택지:\n문 안으로 들어간다.\n돌아선다.\n]]\n\n[[씬:문 안으로 들어간다.\n어둠 속에서 작은 불빛이 떠올랐다.\n]]",
        authorNote: "",
        status: "published",
        publishAt: now(),
        isPaid: false,
        price: 0,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: ep1,
        workId,
        episodeNo: 1,
        requiredPreviousEpisodeNo: 0,
        title: "첫 번째 문장",
        body: "문장 하나가 나무껍질 위에서 빛났다.",
        authorNote: "",
        status: "queued",
        publishAt: "",
        isPaid: false,
        price: 0,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    releases: [],
    noticeTemplates: [
      {
        id: id("template"),
        noticeCode,
        title: "연재 안내",
        body: "이번 주는 월, 수, 금 오후 6시에 공개됩니다.",
        noticeType: "manual",
        createdAt: now(),
        updatedAt: now(),
        isAutoGenerated: false,
      },
    ],
    workNotices: [
      { id: id("work_notice"), workId, noticeCode, createdAt: now(), updatedAt: now(), isAutoGenerated: false },
    ],
    homeIndex: [],
    authorState: { selectedWorkId: workId, editorDrafts: {}, lastSavedAt: "", unsavedChanges: false },
  };
}

function ensureFantasySample(state) {
  const worldId = "sample_fantasy_world_astral";
  const workId = "sample_fantasy_work_astral";
  const episodeIds = ["sample_fantasy_ep_1", "sample_fantasy_ep_2", "sample_fantasy_ep_3"];
  const characterIds = ["sample_fantasy_char_princess", "sample_fantasy_char_knight", "sample_fantasy_char_mage"];
  const itemIds = ["sample_fantasy_item_compass", "sample_fantasy_item_sword", "sample_fantasy_item_potion"];
  const createdAt = "2026-05-30T00:00:00.000Z";
  if (!state.worldbuildings.some((world) => world.id === worldId)) {
    state.worldbuildings.push({
      id: worldId,
      ownerUserId: CURRENT_USER_ID,
      title: "별빛 제국 세계관",
      description: "황녀, 검은 기사, 별의 마법이 얽힌 테스트용 판타지 세계관입니다.",
      sourceScope: "me",
      externalSourceName: "",
      externalAuthorName: "",
      externalSourceLink: "",
      workIds: [workId],
      itemIds: [...itemIds],
      characterIds: [...characterIds],
      createdAt,
      updatedAt: createdAt,
    });
  }
  if (!state.works.some((work) => work.id === workId)) {
    state.works.push({
      id: workId,
      title: "별빛 제국의 문장술사",
      type: "interactive",
      userId: CURRENT_USER_ID,
      temporaryAuthorNickname: "은하필경사",
      temporaryAuthorNicknameUpdatedAt: createdAt,
      description: "별빛으로 문장을 새기는 제국에서 황녀와 검은 기사가 금서의 문을 여는 판타지 테스트 작품입니다.",
      genre1: "여성향",
      genre2: "창작 웹소설",
      normalTags: ["FANTASY", "마법", "황녀", "기사"],
      sensitiveTags: [],
      isAdult: "all",
      adultEditable: true,
      status: "serializing",
      isPaidWork: false,
      cover: { mode: "color", color: "#315c8b", showTitle: true },
      createdAt,
      updatedAt: createdAt,
      episodeOrder: [...episodeIds],
      worldbuildingId: worldId,
      releaseSettings: { method: "regular", days: ["화", "목", "토"], hour: "21", minute: "00", timezone: "Asia/Seoul" },
      views: 340,
      favorites: 42,
      comments: 8,
      nextEpisodeWaiters: 31,
      queueMaxSlots: 3,
      queueSupportTickets: 2,
      queueShowEmptySlots: true,
    });
  }
  const sampleCharacters = [
    {
      id: characterIds[0],
      worldbuildingId: worldId,
      name: "황녀",
      authorLabel: "황녀",
      fullName: "엘리시아 루미나",
      publicDescription: "별빛 문장을 읽는 제국의 황녀입니다.",
      privateDescription: "금서의 첫 문장을 이미 알고 있습니다.",
      tags: ["황녀", "왕가", "별빛"],
      image: "",
    },
    {
      id: characterIds[1],
      worldbuildingId: worldId,
      name: "검은기사",
      authorLabel: "검은기사",
      fullName: "카이론 발렌",
      publicDescription: "황녀를 호위하는 침묵의 기사입니다.",
      privateDescription: "잃어버린 북부 왕가의 후계자입니다.",
      tags: ["기사", "왕가", "북부"],
      image: "",
    },
    {
      id: characterIds[2],
      worldbuildingId: worldId,
      name: "대마법사",
      authorLabel: "대마법사",
      fullName: "세르하 루엔",
      publicDescription: "제국 천문탑의 주인입니다.",
      privateDescription: "별의나침반을 만든 장본인입니다.",
      tags: ["마법사", "천문탑", "마도구"],
      image: "",
    },
  ];
  sampleCharacters.forEach((character) => {
    const existing = state.characters.find((entry) => entry.id === character.id);
    if (existing) {
      existing.tags = existing.tags?.length ? existing.tags : character.tags;
    } else {
      state.characters.push({ ...character, createdAt, updatedAt: createdAt });
    }
  });
  const sampleItems = [
    {
      id: itemIds[0],
      worldbuildingId: worldId,
      ownerUserId: CURRENT_USER_ID,
      name: "별의나침반",
      type: "main",
      priority: 3,
      tags: ["마도구", "별빛", "탐색"],
      itemKind: "normal",
      defaultAddMessage: "별의나침반이 북쪽이 아닌 운명을 가리켰다.",
      defaultRemoveMessage: "별의나침반의 빛이 꺼졌다.",
    },
    {
      id: itemIds[1],
      worldbuildingId: worldId,
      ownerUserId: CURRENT_USER_ID,
      name: "용린검",
      type: "main",
      priority: 2,
      tags: ["무기", "용", "왕가"],
      itemKind: "normal",
      defaultAddMessage: "용린검이 손안에서 낮게 울었다.",
      defaultRemoveMessage: "용린검이 칼집 속으로 잠들었다.",
    },
    {
      id: itemIds[2],
      worldbuildingId: worldId,
      ownerUserId: CURRENT_USER_ID,
      name: "달빛물약",
      type: "sub",
      priority: 1,
      tags: ["소모품", "회복", "연금술"],
      itemKind: "normal",
      defaultAddMessage: "달빛물약을 얻었다.",
      defaultRemoveMessage: "달빛물약을 사용했다.",
    },
  ];
  sampleItems.forEach((item) => {
    const existing = state.items.find((entry) => entry.id === item.id);
    if (existing) {
      existing.tags = existing.tags?.length ? existing.tags : item.tags;
    } else {
      state.items.push({ ...item, createdAt, updatedAt: createdAt });
    }
  });
  const sampleEpisodes = [
    {
      id: episodeIds[0],
      workId,
      episodeNo: 1,
      requiredPreviousEpisodeNo: "",
      title: "별이 떨어진 밤",
      body: "제국의 하늘에서 가장 오래된 별이 떨어졌다.\n\n엘리시아 루미나는 깨진 천문판 앞에서 피 묻은 문장을 읽었다.\n\n[[+별의나침반]]\n별의나침반이 북쪽이 아닌 운명을 가리켰다.",
      authorNote: "테스트용 판타지 샘플 1화입니다.",
      status: "published",
    },
    {
      id: episodeIds[1],
      workId,
      episodeNo: 2,
      requiredPreviousEpisodeNo: 1,
      title: "검은 기사의 서약",
      body: "새벽 종이 울리기 전, 카이론 발렌이 황녀 앞에 무릎을 꿇었다.\n\n[[선택지:\n별의나침반을 건넨다 [[있다면:별의나침반]]\n용린검을 찾으러 간다\n]]\n\n[[씬:별의나침반을 건넨다\n나침반의 바늘이 검은 기사의 심장을 향했다.\n[[+용린검]]\n]]",
      authorNote: "선택지와 아이템 조건 확인용 샘플입니다.",
      status: "published",
    },
    {
      id: episodeIds[2],
      workId,
      episodeNo: 3,
      requiredPreviousEpisodeNo: 2,
      title: "천문탑의 금서",
      body: "#마도구 전체가 붙은 물건들은 밤이 깊을수록 스스로 빛났다.\n\n세르하 루엔은 금서의 봉인을 풀며 말했다.\n\n[[+달빛물약]]\n달빛물약을 얻었다.\n\n[[-별의나침반]]\n별의나침반의 빛이 금서 속으로 빨려 들어갔다.",
      authorNote: "태그 검색과 아이템 소실 문법 확인용 샘플입니다.",
      status: "queued",
    },
  ];
  sampleEpisodes.forEach((episode) => {
    const existing = state.episodes.find((entry) => entry.id === episode.id);
    if (existing) {
      const hasLegacySearchText = /[@#][^\s\]]+:"/.test(existing.body || "");
      if (hasLegacySearchText) {
        existing.body = episode.body;
        existing.updatedAt = createdAt;
      }
    } else {
      state.episodes.push({
        ...episode,
        publishAt: episode.status === "published" ? createdAt : "",
        isPaid: false,
        price: 0,
        createdAt,
        updatedAt: createdAt,
      });
    }
  });
  if (!state.homeIndex.some((entry) => entry.workId === workId)) {
    state.homeIndex.push({ workId, episodeId: episodeIds[0], publishedAt: createdAt });
    state.homeIndex.push({ workId, episodeId: episodeIds[1], publishedAt: createdAt });
  }
  return state;
}

function normalize(state) {
  const fallback = seedState();
  if (!state || typeof state !== "object" || Array.isArray(state)) state = fallback;
  if (!Array.isArray(state.users)) state.users = fallback.users;
  if (!state.authorProfile || typeof state.authorProfile !== "object" || Array.isArray(state.authorProfile)) state.authorProfile = fallback.authorProfile;
  if (!Array.isArray(state.works)) state.works = [];
  if (!Array.isArray(state.worldbuildings)) state.worldbuildings = [];
  if (!Array.isArray(state.characters)) state.characters = [];
  if (!Array.isArray(state.items)) state.items = [];
  if (!Array.isArray(state.episodes)) state.episodes = [];
  if (!Array.isArray(state.releases)) state.releases = [];
  if (!Array.isArray(state.noticeTemplates)) state.noticeTemplates = [];
  if (!Array.isArray(state.workNotices)) state.workNotices = [];
  if (!Array.isArray(state.homeIndex)) state.homeIndex = [];
  ensureFantasySample(state);
  state.authorState ||= fallback.authorState;
  state.users[0] ||= fallback.users[0];
  state.users[0].officialNickname ||= "나무나비";
  state.users[0].officialNicknameChangeTickets ??= 1;
  state.users[0].temporaryAuthorNicknameChangeTickets ??= 1;
  state.users[0].queueAddTickets ??= 2;
  state.authorProfile.workspaceTitle ||= "숲글 작가 작업실";
  if (state.authorProfile.readerGenreDisplay1 === "자유") state.authorProfile.readerGenreDisplay1 = "마음대로";
  state.authorProfile.readerGenreDisplay1 ||= "여성향";
  state.authorProfile.readerGenreDisplay2 ||= "창작 웹소설";
  state.authorProfile.adultVerificationStatus ||= "none";
  state.works.forEach((work) => {
    work.userId ||= CURRENT_USER_ID;
    if (work.genre1 === "자유") work.genre1 = "마음대로";
    work.normalTags ||= work.workTags || [];
    work.sensitiveTags ||= [];
    work.episodeOrder ||= [];
    work.releaseSettings ||= { method: "irregular", days: [], hour: "18", minute: "00", timezone: "Asia/Seoul" };
    work.cover ||= { mode: "color", color: "#47645e", showTitle: true };
    work.cover.mode ||= "color";
    work.cover.color ||= "#47645e";
    work.cover.imageData ||= "";
    work.cover.imageName ||= "";
    work.nextEpisodeWaiters ??= 0;
    work.queueMaxSlots ??= 1;
    work.queueSupportTickets ??= 2;
    work.queueShowEmptySlots ??= true;
  });
  state.worldbuildings.forEach((world) => {
    world.sourceScope ||= "me";
    world.externalSourceName ||= "";
    world.externalAuthorName ||= "";
    world.externalSourceLink ||= "";
  });
  state.characters.forEach((character) => {
    character.authorLabel ||= character.name || "";
    character.name ||= character.authorLabel;
    character.fullName ||= "";
    character.image ||= "";
    character.tags ||= [];
  });
  state.episodes.forEach((episode) => {
    episode.requiredPreviousEpisodeNo ??= "";
    if (episode.status === "reserved") episode.status = "confirmed";
  });
  return state;
}

let cache = null;

export function loadState() {
  if (cache) return cache;
  const raw = localStorage.getItem(STORAGE_KEY);
  let parsed = null;
  try {
    parsed = raw ? JSON.parse(raw) : seedState();
  } catch {
    parsed = seedState();
  }
  cache = normalize(parsed);
  saveState(cache);
  return cache;
}

export function saveState(state = cache) {
  cache = normalize(state || seedState());
  localStorage.setItem(STORAGE_KEY, JSON.stringify(cache));
}

export function resetState() {
  cache = seedState();
  saveState(cache);
  return cache;
}

export function exportState() {
  return JSON.stringify(loadState(), null, 2);
}

export function timestamp() {
  return now();
}

export function uid(prefix) {
  return id(prefix);
}

export function currentUser() {
  return loadState().users.find((user) => user.id === CURRENT_USER_ID) || loadState().users[0];
}

export function displayAuthor(work) {
  if (work.temporaryAuthorNickname) return work.temporaryAuthorNickname;
  return loadState().users.find((user) => user.id === work.userId)?.officialNickname || "작가명 없음";
}

export function workWorld(work) {
  return loadState().worldbuildings.find((world) => world.id === work.worldbuildingId);
}

export function workEpisodes(workId) {
  return loadState()
    .episodes.filter((episode) => episode.workId === workId)
    .sort((a, b) => Number(a.episodeNo) - Number(b.episodeNo));
}

export function noticeTemplate(noticeCode) {
  return loadState().noticeTemplates.find((notice) => notice.noticeCode === noticeCode);
}

export function upsert(collection, entity) {
  const state = loadState();
  const list = state[collection];
  const index = list.findIndex((item) => item.id === entity.id);
  if (index >= 0) list[index] = { ...list[index], ...entity, updatedAt: now() };
  else list.push({ ...entity, createdAt: now(), updatedAt: now() });
  saveState(state);
  return entity;
}
